name: Nightly Push

on:
  schedule:
    - cron:  '0 8 * * *' # every day at 8 am UTC / 1 am PDT / 4 am EDT

jobs:
  deploy-nightly:
    if: github.repository_owner == 'facebookexperimental'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # config GIT so it can do git push
    - uses: fregante/setup-git-user@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm i -g yarn
    - run: yarn install --frozen-lockfile
    - run: yarn deploy-nightly
